name: Run Tests and Deploy Report

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and run tests
        run: mvn clean test

      - name: Copy report to docs folder
        run: |
          mkdir -p docs
          cp -r target/cucumber-reports.html docs/

      - name: Commit report
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add docs/
          git commit -m "Update test report [skip ci]" || echo "No changes to commit"
          git push origin main
